# Generated by Django 2.0.7 on 2021-09-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0003_auto_20210918_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Duration',
            field=models.FloatField(default=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Instructor_Name',
            field=models.CharField(default=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(default=False, max_length=60),
        ),
    ]
