# Generated by Django 2.0.7 on 2021-09-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0004_auto_20210919_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Instructor_Name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(default='', max_length=60),
        ),
    ]
