# Generated by Django 2.0.7 on 2021-09-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0005_auto_20210919_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('SQL', 'SQL'), ('Javascript', 'Javascript'), ('Python', 'Python'), ('C#', 'C#')], default='', max_length=60),
        ),
    ]
