# Generated by Django 2.0.7 on 2021-09-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0006_auto_20210919_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(choices=[('001', '001'), ('003', '003'), ('004', '004'), ('002', '002')], default=True),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('SQL', 'SQL'), ('Javascript', 'Javascript'), ('C#', 'C#'), ('Python', 'Python')], default='', max_length=60),
        ),
    ]
