# Generated by Django 2.0.7 on 2021-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0007_auto_20210919_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='Course_Number',
            field=models.IntegerField(choices=[('003', '003'), ('004', '004'), ('001', '001'), ('002', '002')], default=True),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Duration',
            field=models.FloatField(choices=[('2 yr', '2 yr'), ('6 mnth', '6 mnth'), ('1 yr', '1 yr')], default=False, max_length=1000),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='Title',
            field=models.CharField(choices=[('Python', 'Python'), ('C#', 'C#'), ('SQL', 'SQL'), ('Javascript', 'Javascript')], default='', max_length=60),
        ),
    ]
