# Generated by Django 2.0.7 on 2021-09-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('Course_Number', models.CharField(max_length=60)),
                ('Instructor_Name', models.CharField(max_length=60)),
                ('Duration', models.CharField(max_length=60)),
            ],
        ),
    ]
